`default_nettype none
module darkriscv_soc (
    input  wire        clk,
    input  wire        rst_n,
    input  wire        uart_rx,
    output wire        uart_tx,
    input  wire [3:0]  gpio_in,
    output wire [7:0]  gpio_out,
    output wire [3:0]  debug
);
    wire reset = ~rst_n;
    wire idreq, idack, iberr;
    wire [31:0] iaddr, idata;
    wire ddreq, drw, drd, dwr, ddack, dberr;
    wire [31:0] daddr, datao, datai;
    wire [2:0] dlen;
    wire [3:0] dbe;

    reg [31:0] gpio_reg;
    reg [7:0] uart_reg;
    reg [31:0] dmem [0:63];

    // A tiny immutable boot program. It increments GPIO forever.
    // Replace this function with firmware generated by tools/bin2rom.py.
    function automatic [31:0] boot_word(input [7:0] word_addr);
        begin
            case (word_addr)
                8'd0: boot_word = 32'h4000_00b7; // lui  x1,0x40000
                8'd1: boot_word = 32'h0000_0113; // addi x2,x0,0
                8'd2: boot_word = 32'h0011_0113; // addi x2,x2,1
                8'd3: boot_word = 32'h0020_a023; // sw   x2,0(x1)
                8'd4: boot_word = 32'hff9f_f06f; // jal  x0,-8
                default: boot_word = 32'h0000_0013; // nop
            endcase
        end
    endfunction

    assign idata = boot_word(iaddr[9:2]);
    assign idack = idreq;
    assign iberr = idreq && (iaddr[31:10] != 0);

    wire gpio_sel = (daddr[31:12] == 20'h40000);
    wire dmem_sel = (daddr[31:8]  == 24'h100000);
    wire [5:0] dmem_index = daddr[7:2];
    assign datai = gpio_sel ? ((daddr[5:2] == 4'd0) ? gpio_reg :
                              (daddr[5:2] == 4'd1) ? {24'b0, uart_rx, gpio_in, 3'b0} :
                              32'b0) :
                   dmem_sel ? dmem[dmem_index] : 32'b0;
    assign ddack = ddreq;
    assign dberr = ddreq && !(gpio_sel || dmem_sel);

    integer k;
    always @(posedge clk) begin
        if (reset) begin
            gpio_reg <= 32'b0;
            uart_reg <= 8'hff;
            for (k = 0; k < 64; k = k + 1)
                dmem[k] <= 32'b0;
        end else if (dwr && ddreq && ddack) begin
            if (gpio_sel && daddr[5:2] == 4'd0) begin
                if (dbe[0]) gpio_reg[7:0]   <= datao[7:0];
                if (dbe[1]) gpio_reg[15:8]  <= datao[15:8];
                if (dbe[2]) gpio_reg[23:16] <= datao[23:16];
                if (dbe[3]) gpio_reg[31:24] <= datao[31:24];
            end
            if (gpio_sel && daddr[5:2] == 4'd1 && dbe[0])
                uart_reg <= datao[7:0];
            if (dmem_sel) begin
                if (dbe[0]) dmem[dmem_index][7:0]   <= datao[7:0];
                if (dbe[1]) dmem[dmem_index][15:8]  <= datao[15:8];
                if (dbe[2]) dmem[dmem_index][23:16] <= datao[23:16];
                if (dbe[3]) dmem[dmem_index][31:24] <= datao[31:24];
            end
        end
    end

    assign gpio_out = gpio_reg[7:0];
    assign uart_tx = uart_reg[0];

    darkriscv u_cpu (
        .CLK(clk), .RES(reset),
        .IDREQ(idreq), .IADDR(iaddr), .IDATA(idata), .IDACK(idack), .IBERR(iberr),
        .DDREQ(ddreq), .DADDR(daddr), .DLEN(dlen), .DBE(dbe), .DRW(drw),
        .DRD(drd), .DWR(dwr), .DATAO(datao), .DATAI(datai), .DDACK(ddack), .DBERR(dberr),
        .DEBUG(debug)
    );
endmodule
`default_nettype wire
